const images = {
  PageNotFound: require("./Assets/Images/page-not-found-img.svg").default,
  //action plan icons
  userManagement: require("./Assets/Images/UserManagement.svg").default,
  dashboard: require("./Assets/Images/Dashboard.svg").default,
  activeAssessment: require("./Assets/Images/activeAssessment.svg").default,
  pastAssessment: require("./Assets/Images/pastAssessment.svg").default,
  actionPlan: require("./Assets/Images/actionPlan.svg").default,
  searchIcon: require("./Assets/Images/search.svg").default,
  filterIcon: require("./Assets/Images/filterGray.svg").default,
  dropdown: require("./Assets/Images/dropdown.svg").default,
  deleteIcon: require("./Assets/Images/delete.svg").default,
  pdfDownload: require("./Assets/Images/pdf.svg").default,
  edit: require("./Assets/Images/edit.svg").default,
  comment: require("./Assets/Images/comment.svg").default,
  dueDate: require("./Assets/Images/duedate.svg").default,
  confirmAlert: require("./Assets/Images/deleteAlert.svg").default,
  attachment: require("./Assets/Images/attachment.svg").default,
  deadline: require("./Assets/Images/deadline.svg").default,
  upArrow: require("./Assets/Images/uparrow.svg").default,
  commentTitle: require("./Assets/Images/commentTitle.svg").default,
  recentActivity: require("./Assets/Images/recentActivity.svg").default,
  group: require("./Assets/Images/Group.svg").default,
  email: require("./Assets/Images/mail.svg").default,
  password: require("./Assets/Images/password.svg").default,
  eye: require("./Assets/Images/eye.svg").default,
  hidePassword: require("./Assets/Images/hidePassword.svg").default,
  loginPage: require("./Assets/Images/loginPage.svg").default,
  updaptLogo: require("./Assets/Images/updaptLogo.svg").default,
  emailGrey: require("./Assets/Images/emailGrey.svg").default,
  passwordGrey: require("./Assets/Images/passwordGrey.svg").default,
  eyeSlash: require("./Assets/Images/eyeSlash.svg").default,
  eyeSlashGrey: require("./Assets/Images/eyeSlashGrey.svg").default,
  bellIcon: require("./Assets/Images/bellIcon.svg").default,
  blueFilter: require("./Assets/Images/filterBlue.svg").default,
  disableEdit: require("./Assets/Images/disableEdit.svg").default,
};
export default images;
