// let images = {};

// if (process.env.NODE_ENV === "development") {
let images = {
  //dev
  teamFameLogo: require("./Assets/Images/teamFameLogo.svg").default,
  teamGroupPic: require("./Assets/Images/teamGroupPic.svg").default,
  fameRevolutionLogo: require("./Assets/Images/FameRevolutionLogo.svg").default,
  educationLogo: require("./Assets/Images/educationLogo.svg").default,
  sportsLogo: require("./Assets/Images/sportsLogo.svg").default,
  spiritualityLogo: require("./Assets/Images/spiritualityLogo.svg").default,
  lawLogo: require("./Assets/Images/lawLogo.svg").default,
  missionHandImage: require("./Assets/Images/missionHandImage.svg").default,
  flowerHorizontal: require("./Assets/Images/flowerHorizontal.svg").default,
  invertedCommas: require("./Assets/Images/invertedCommas.svg").default,
  comma: require("./Assets/Images/comma.svg").default,
  eventBackground: require("./Assets/Images/eventBackground.svg").default,
  cardLabelSide: require("./Assets/Images/cardLabelSide.svg").default,
  eventMom: require("./Assets/Images/eventMom.svg").default,
  facebook: require("./Assets/Images/facebook.svg").default,
  instagram: require("./Assets/Images/instagram.svg").default,
  whatsapp: require("./Assets/Images/whatsapp.svg").default,
  mission: require("./Assets/Images/mission.svg").default,
  videoThumbnail: require("./Assets/Images/videoThumbnail.png").default,
  testimonial: require("./Assets/Images/testimonial.svg").default,
  cancelButton: require("./Assets/Images/cancelButton.svg").default,
  settings: require("./Assets/Images/configuration.svg").default,

  aboutusIcon: require("./Assets/Images/about-us.svg").default,
  eventIcon: require("./Assets/Images/Events.svg").default,
  videoIcon: require("./Assets/Images/Videos.svg").default,
  testimonialIcon: require("./Assets/Images/testimonialsIcon.svg").default,
  newsIcon: require("./Assets/Images/news.svg").default,
  schemeIcon: require("./Assets/Images/Scheme.svg").default,
  AddProfilePhotoPlus: require("./Assets/Images/AddProfilePhotoPlus.svg")
    .default,
  guestUSer: require("./Assets/Images/guestUser.svg").default,
  goldSchemeCovered: require("./Assets/Images/goldSchemeCovered.svg").default,
  Rectangle: require("./Assets/Images/Rectangle.svg").default,
  locket: require("./Assets/Images/locket.svg").default,
  cart: require("./Assets/Images/cart.svg").default,
  storeImage: require("./Assets/Images/storeImage.svg").default,
  chair: require("./Assets/Images/chair.svg").default,
  viewMore: require("./Assets/Images/viewMore.svg").default,
  eventsHeader: require("./Assets/Images/eventsHeader.svg").default,
  eventCard: require("./Assets/Images/eventCard.svg").default,
  videoBackGround: require("./Assets/Images/videoBackGround.svg").default,
  videoAdd: require("./Assets/Images/videoAdd.svg").default,
  birlaLogo: require("./Assets/Images/birlaLogo.svg").default,
  jewLogo: require("./Assets/Images/jewLogo.svg").default,
  userProfile: require("./Assets/Images/userprofile.svg").default,
  // };
  // } else {
  //   images = {
  PageNotFound: require("./Assets/Images/page-not-found-img.svg"),
  //action plan icons
  userManagement: require("./Assets/Images/UserManagement.svg").default,
  dashboard: require("./Assets/Images/Dashboard.svg").default,
  activeAssessment: require("./Assets/Images/activeAssessment.svg").default,
  pastAssessment: require("./Assets/Images/pastAssessment.svg").default,
  actionPlan: require("./Assets/Images/actionPlan.svg").default,
  searchIcon: require("./Assets/Images/search.svg").default,
  filterIcon: require("./Assets/Images/filterGray.svg").default,
  dropdown: require("./Assets/Images/dropdown.svg").default,
  deleteIcon: require("./Assets/Images/delete.svg").default,
  pdfDownload: require("./Assets/Images/pdf.svg").default,
  edit: require("./Assets/Images/edit.svg").default,
  comment: require("./Assets/Images/comment.svg").default,
  dueDate: require("./Assets/Images/duedate.svg").default,
  confirmAlert: require("./Assets/Images/deleteAlert.svg").default,
  attachment: require("./Assets/Images/attachment.svg").default,
  deadline: require("./Assets/Images/deadline.svg").default,
  upArrow: require("./Assets/Images/uparrow.svg").default,
  commentTitle: require("./Assets/Images/commentTitle.svg").default,
  recentActivity: require("./Assets/Images/recentActivity.svg").default,
  group: require("./Assets/Images/Group.svg").default,
  email: require("./Assets/Images/mail.svg").default,
  password: require("./Assets/Images/password.svg").default,
  eye: require("./Assets/Images/eye.svg").default,
  hidePassword: require("./Assets/Images/hidePassword.svg").default,
  loginPage: require("./Assets/Images/loginPage.svg").default,
  updaptLogo: require("./Assets/Images/updaptLogo.svg").default,
  emailGrey: require("./Assets/Images/emailGrey.svg"),
  passwordGrey: require("./Assets/Images/passwordGrey.svg"),
  eyeSlash: require("./Assets/Images/eyeSlash.svg").default,
  eyeSlashGrey: require("./Assets/Images/eyeSlashGrey.svg").default,
  bellIcon: require("./Assets/Images/bellIcon.svg"),
  blueFilter: require("./Assets/Images/filterBlue.svg").default,
  disableEdit: require("./Assets/Images/disableEdit.svg").default,
  storeAS: require("./Assets/Images/storeAS.svg").default,
  orderDetailsAS: require("./Assets/Images/orderDetailsAS.svg").default,
  // PageNotFound: require("./Assets/Images/page-not-found-img.svg").default,
  logoBackground: require("./Assets/Images/logoBackground.svg").default,
  adityaCapital: require("./Assets/Images/adityaCapital.svg").default,

  //prod
  // PageNotFound: require("./Assets/Images/page-not-found-img.svg"),
  // teamFameLogo: require("./Assets/Images/teamFameLogo.svg"),
  // teamGroupPic: require("./Assets/Images/teamGroupPic.svg"),
  // logoBackground: require("./Assets/Images/logoBackground.jpg"),
  // fameRevolutionLogo: require("./Assets/Images/FameRevolutionLogo.svg"),
  // educationLogo: require("./Assets/Images/educationLogo.svg"),
  // sportsLogo: require("./Assets/Images/sportsLogo.svg"),
  // spiritualityLogo: require("./Assets/Images/spiritualityLogo.svg"),
  // lawLogo: require("./Assets/Images/lawLogo.svg"),
  // missionHandImage: require("./Assets/Images/missionHandImage.svg"),
  // flowerHorizontal: require("./Assets/Images/flowerHorizontal.svg"),
  // invertedCommas: require("./Assets/Images/invertedCommas.svg"),
  // comma: require("./Assets/Images/comma.svg"),
  // eventBackground: require("./Assets/Images/eventBackground.svg"),
  // cardLabelSide: require("./Assets/Images/cardLabelSide.svg"),
  // eventMom: require("./Assets/Images/eventMom.svg"),
  // facebook: require("./Assets/Images/facebook.svg"),
  // instagram: require("./Assets/Images/instagram.svg"),
  // whatsapp: require("./Assets/Images/whatsapp.svg"),
  // mission: require("./Assets/Images/mission.svg"),
  // videoThumbnail: require("./Assets/Images/videoThumbnail.png"),
  // testimonial: require("./Assets/Images/testimonial.svg"),
  // cancelButton: require("./Assets/Images/cancelButton.svg"),
  // settings: require("./Assets/Images/configuration.svg"),
  // confirmAlert: require("./Assets/Images/deleteAlert.svg"),
  // pdfDownload: require("./Assets/Images/pdf.svg"),

  // aboutusIcon: require("./Assets/Images/about-us.svg"),
  // eventIcon: require("./Assets/Images/Events.svg"),
  // videoIcon: require("./Assets/Images/Videos.svg"),
  // testimonialIcon: require("./Assets/Images/testimonialsIcon.svg"),
  // newsIcon: require("./Assets/Images/news.svg"),
  // schemeIcon: require("./Assets/Images/Scheme.svg"),
  // AddProfilePhotoPlus: require("./Assets/Images/AddProfilePhotoPlus.svg"),
  // guestUSer: require("./Assets/Images/guestUser.svg"),
  // goldSchemeCovered: require("./Assets/Images/goldSchemeCovered.svg"),
  // Rectangle: require("./Assets/Images/Rectangle.svg"),
  // locket: require("./Assets/Images/locket.svg"),
  // cart: require("./Assets/Images/cart.svg"),
  // storeImage: require("./Assets/Images/storeImage.svg"),
  // chair: require("./Assets/Images/chair.svg"),
  // viewMore: require("./Assets/Images/viewMore.svg"),
  // eventsHeader: require("./Assets/Images/eventsHeader.svg"),
  // eventCard: require("./Assets/Images/eventCard.svg"),
  // videoBackGround: require("./Assets/Images/videoBackGround.svg"),
  // videoAdd: require("./Assets/Images/videoAdd.svg"),
  // birlaLogo: require("./Assets/Images/birlaLogo.svg"),
  // jewLogo: require("./Assets/Images/jewLogo.svg"),
  // userProfile: require("./Assets/Images/userprofile.svg"),
  // storeAS: require("./Assets/Images/storeAS.svg"),
  // orderDetailsAS: require("./Assets/Images/orderDetailsAS.svg"),
  // adityaCapital: require("./Assets/Images/adityaCapital.svg"),
};
export default images;
